/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Kevin Barahona
 */
public class FileDialog extends javax.swing.JFrame {

    /**
     * Creates new form FileDialog
     */
    boolean editMode = false;
    DefaultMutableTreeNode parent = null;
    private JTree tree = null;
    private entryNode editNode = null;

    public FileDialog(boolean edit, DefaultMutableTreeNode parent) {
        initComponents();
        editMode = edit;
        this.parent = parent;
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if (editMode) {
            fileName.setEditable(false);
        }
    }

    public FileDialog(boolean edit, entryNode editNode, DefaultMutableTreeNode parent, JTree tree) throws RemoteException {
        initComponents();
        editMode = edit;
        this.parent = parent;
        this.tree = tree;
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if (editMode) {
            this.editNode = editNode;
            fileName.setText(editNode.getName());
            fileContent.setText(Client.Server.streamFromServer(editNode));
            fileName.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileContent = new javax.swing.JTextArea();
        fileName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("File Name:");

        fileContent.setColumns(20);
        fileContent.setRows(5);
        jScrollPane1.setViewportView(fileContent);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!editMode) {
            String Text = fileContent.getText();
            try {
                if (!Client.Server.addFile(fileName.getText(), parent, Text)) {
                    System.out.println("No se pudo");
                }
                this.setVisible(false);
                tree.setModel(Client.Server.getTreeModel());
                ((DefaultTreeModel) tree.getModel()).reload();
            } catch (RemoteException ex) {
                Logger.getLogger(FileDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            String Text = fileContent.getText();
            try {
                if (!Client.Server.editFile(fileName.getText(), editNode, Text)) {
                    System.out.println("No se pudo");
                }
                this.setVisible(false);
                tree.setModel(Client.Server.getTreeModel());
                ((DefaultTreeModel) tree.getModel()).reload();
            } catch (RemoteException ex) {
                Logger.getLogger(FileDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea fileContent;
    private javax.swing.JTextField fileName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
